name: wrmxpress_gui
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ag-grid
  - appnope
  - asttokens
  - blinker
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - click
  - comm
  - dash
  - dash-ag-grid
  - dash-bootstrap-components
  - dash-core-components
  - dash-html-components
  - dash-table
  - debugpy
  - decorator
  - eigen
  - exceptiongroup
  - executing
  - expat
  - ffmpeg
  - flask
  - flask-compress
  - fontconfig
  - freetype
  - gettext
  - giflib
  - glib
  - glib-tools
  - gmp
  - gnutls
  - graphite2
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - hdf5
  - icu
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - itsdangerous
  - jedi
  - jinja2
  - jpeg
  - jupyter_client
  - jupyter_core
  - krb5
  - lame
  - lcms2
  - lerc
  - libblas
  - libcblas
  - libclang
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libexpat
  - libffi
  - libgfortran
  - libgfortran5
  - libglib
  - libiconv
  - libidn2
  - liblapack
  - libllvm12
  - libnghttp2
  - libopenblas
  - libopus
  - libpng
  - libpq
  - libsodium
  - libsqlite
  - libssh2
  - libtasn1
  - libtiff
  - libunistring
  - libvpx
  - libwebp
  - libwebp-base
  - libxml2
  - libxslt
  - libzlib
  - llvm-openmp
  - markupsafe
  - matplotlib-inline
  - ncurses
  - nest-asyncio
  - nettle
  - nspr
  - nss
  - numpy
  - opencv
  - openh264
  - openjpeg
  - openssl
  - packaging
  - pandas
  - parso
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - platformdirs
  - plotly
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pygments
  - python-dateutil
  - python_abi
  - pytz
  - pyyaml
  - pyzmq
  - qt-main
  - qt-webengine
  - qtwebkit
  - readline
  - setuptools
  - six
  - sqlite
  - stack_data
  - tenacity
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - wcwidth
  - werkzeug
  - wheel
  - x264
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
