site_name: wrmXpress-gui
# site_url: https://example.com  # Customize with your project URL
site_description: This is the documentation for the wrmXpress-gui package.

theme: readthedocs

nav:
  - Home: index.md
  - Data Organization: data_organization.md
  - Configuration:
    - Instrument Settings: instrument_settings.md
    - Image Transformations: image_transformations.md
    - Pipeline Selection:
      - Motility: pipelines/motility.md
      - Development: pipelines/development.md
      - Fecundity: pipelines/fecundity.md
      - Toxicity: pipelines/toxicity.md
      - Feeding: pipelines/feeding.md
    - Run Diagnostics: dx.md
    - Run-Time Settings: run_time.md
  - Metadata:
    - Adding Metadata: metadata.md
  - Preview: 
    - Testing pipelines: preview.md
  - Run:
    - Running full analyses: run.md
plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - admonition  # Enables 'Note' and 'Warning' blocks
  - codehilite  # Enables syntax highlighting for code blocks
  - toc         # Generates a table of contents for each page
  - attr_list

